from django.conf.urls import url
from evesch.core import views
from evesch.euser import views as euser_views

urlpatterns = [
    url(r'^login/$',
        views.evesch_login,
        {'template_name': 'core/login.html'},
        name='account_auth_login'),
    url(r'^logout/$',
        views.evesch_logout,
        {'template_name': 'core/login.html'},
        name='account_auth_logout'),
    url(r'^signup/$',
        views.evesch_signup,
        {'template_name': 'core/signup.html'},
        name='account_signup'),
    url(r'^signup/confirm/',
        views.evesch_signup_confirm,
        {'template_name': 'core/signup_confirm.html'},
        name='account_signup_confirm'),
    url(r'^signup/success/',
        views.evesch_signup_success,
        {'template_name': 'core/signup_success.html'},
        name='account_signup_success'),
    url(r'^signup/captcha.png$',
        views.evesch_captcha,
        {},
        name='account_signup_captcha'),
    url(r'^password_reset/$',
        views.evesch_password_reset,
        {'template_name': 'core/password_reset.html'},
        name='account_password_reset'),
    url(r'^password_reset/sent/$',
        views.evesch_password_reset_sent,
        {'template_name': 'core/password_reset_sent.html'},
        name='account_password_reset_sent'),
    url(r'^settings/$',
        euser_views.user_settings,
        {'template_name': 'euser/user_settings.html'},
        name='euser_user_settings'),
]
