version: '3.4'
services:

   db:
     image: postgres:11.2
     ports:
       - "5432"
     volumes:
       - pg_data:/var/lib/postgresql/data
     healthcheck:
       test: ["CMD", "pg_isready", "-U", "postgres"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3

   app:
     image: joejasinski/evesch:prod-1.0.1
     build:
       context: .
       dockerfile: Dockerfile
     command: /site/docker-utils/app-start.sh
     volumes:
       - .:/site/proj/
       - static-volume:/site/htdocs/static/
     ports:
       - "8000"
     environment:
       - DATABASE_URL=postgres://postgres@db/postgres
       - SITE_DIR=/site/
     depends_on:
       - db
     healthcheck:
       test: ["CMD", "curl", "localhost", "8000"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3
     stdin_open: true
     tty: true

   web:
     image: nginx:1.15-alpine
     depends_on:
       - app
     volumes:
       - ./docker-utils/nginx/default.template.conf:/root/default.template.conf
       - ./docker-utils/ssl/:/site/ssl/
       - static-volume:/static
     command: /bin/sh -c "envsubst '$$NGINX_HTTP_PORT $$NGINX_HTTPS_PORT' < /root/default.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
     environment:
       - NGINX_HOST=foobar.com
       - NGINX_HTTP_PORT=80
       - NGINX_HTTPS_PORT=443
     ports:
       - "443:443"

volumes:
  static-volume:
  pg_data:

