# Generated by Django 2.1.8 on 2019-04-22 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(db_index=True, max_length=64, verbose_name='Organization Name')),
                ('org_short_name', models.SlugField(max_length=20, verbose_name='Organization Short Name')),
                ('org_active', models.BooleanField(default=True, help_text='Does the Organization exist?', verbose_name='Organization Active')),
                ('org_desc', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Organization Description')),
                ('org_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Organization Email')),
                ('org_website', models.URLField(blank=True, null=True, verbose_name='Organization Website')),
                ('org_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Phone Number')),
                ('org_address', models.CharField(blank=True, max_length=100, null=True)),
                ('org_city', models.CharField(blank=True, max_length=80, null=True, verbose_name='Organization City')),
                ('org_state', models.CharField(blank=True, max_length=32, null=True, verbose_name='Organization State')),
                ('org_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Organization Zip Code')),
                ('org_type', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Non Profit'), (2, 'Business'), (3, 'Community'), (4, 'Social'), (5, 'School')], default=0, null=True)),
                ('org_date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('org_feed_hash', models.CharField(blank=True, max_length=20, null=True, verbose_name='Organization Feed Hash')),
                ('org_join_privacy', models.IntegerField(blank=True, choices=[(0, 'Public'), (1, 'Invite Only'), (2, 'Request Membership')], default=0, help_text='<u>Public:</u> any user may join this organization. <BR><u>Invite Only:</u> a user must receive an invitation from someone in the org.  <BR><u>Request Membership:</u> a user must request membership to join that must be confirmed by someone in the org.', null=True, verbose_name='Organization Join Privacy')),
                ('org_browsable', models.BooleanField(default=True, help_text='List this organization in the public Browse directory? (recommended) Authenticated users will still be able to see it.', verbose_name='Browsable')),
            ],
        ),
        migrations.CreateModel(
            name='OrgInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Anonymous email')),
                ('direction', models.BooleanField(default=True)),
                ('invite_hash', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Invite Hash')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_set', to='org.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_invites_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
