# Generated by Django 2.1.8 on 2019-04-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40)),
                ('group_hash', models.SlugField(max_length=16)),
                ('group_desc', models.TextField(blank=True, null=True)),
                ('group_removable', models.BooleanField(default=False)),
                ('admin_org', models.BooleanField(default=False)),
                ('coord_events', models.BooleanField(default=False)),
                ('invite_users', models.BooleanField(default=False)),
                ('meta', models.IntegerField(choices=[(0, 'None'), (1, 'Everyone')], default=0)),
            ],
        ),
    ]
