# Generated by Django 2.1.8 on 2019-04-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('euser', '0001_initial'),
        ('org', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='user_organizations',
            field=models.ManyToManyField(blank=True, related_name='org_users', to='org.Organization', verbose_name='User Organizations'),
        ),
        migrations.AddField(
            model_name='euser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
