# org/urls.py
# included by main_urls.py
from django.conf.urls import include, url
from evesch.org import views
from evesch.core.feed import views as feed_views

urlpatterns = [
    url(r'^$',
        views.orgs_list, 
        {'template_name': 'org/orgs_list.html'},
        name='org_orgs_list'),
    url(r'^ajax/$',
        views.orgs_list, 
        {'template_name': 'org/ajax/ajax_orgs_list_all_entry.html'},
        name='org_orgs_list_ajax'),
    url(r'^ajax/all_orgs/$',
        views.orgs_list_all, 
        {'template_name': 'org/ajax/ajax_orgs_list_all_entry.html'},
        name='org_orgs_list_all_ajax'),    
    url(r'^ajax/my_orgs/$',
        views.orgs_list_my, 
        {'template_name': 'org/ajax/ajax_orgs_list_my_entry.html'},
        name='org_orgs_list_my_ajax'),     
    url(r'^(?P<org_short_name>[\w_-]{1,20})/ajax/members/$',
        views.org_members, 
        {'template_name': 'org/ajax/ajax_org_user_list.html'},
        name='org_org_user_list_ajax'),    
    url(r'^(?P<org_short_name>[\w_-]{1,20})/ajax/invites/$',
        views.org_list_invites, 
        {'template_name': 'org/ajax/ajax_org_user_list.html'},
        name='org_org_invites_list_ajax'), 
    url(r'^add/$',
        views.org_add, 
        {'template_name': 'org/org_add.html'},
        name='org_org_add'), 
    url(r'^browse/$',
        views.org_browse, 
        {'template_name': 'org/org_browse.html'},
        name='org_org_browse'), 
    url(r'^browse/(?P<filter_abc>)[a-z]{1}/$',
        views.org_browse, 
        {'template_name': 'org/org_browse.html'},
         name='org_org_browse_filter_abc'), 
    url(r'^(?P<org_short_name>[\w_-]{1,20})/edit/$',
        views.org_edit, 
        {'template_name': 'org/org_edit.html'},
        name='org_org_edit'), 
    url(r'^(?P<org_short_name>[\w_-]{1,20})/remove/$',
        views.org_remove, 
        {'template_name': 'org/org_remove.html'},
        name='org_org_remove'),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/join/$',
        views.org_join, 
        {'template_name': 'org/org_join.html'},
        name='org_org_join'),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/leave/$',
        views.org_leave, 
        {'template_name': 'org/org_leave.html'},
        name='org_org_leave'),   
    url(r'^(?P<org_short_name>[\w_-]{1,20})/member/remove/(?P<username>\w{1,30})/',
        views.org_member_remove, 
        {'template_name': 'org/org_member_remove.html'},
        name='org_org_member_remove'),      
    url(r'^(?P<org_short_name>[\w_-]{1,20})/members/',
        views.org_members, 
        {'template_name': 'org/org_members.html'},
        name='org_org_members'),  
    url(r'^(?P<org_short_name>[\w_-]{1,20})/$',
        views.org_view, 
        {'template_name': 'org/org_view.html'},
        name='org_org_view'),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/photo/',
        include('evesch.org.avatar.urls')),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/',
        include('evesch.event.urls')),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/group/',
        include('evesch.egroup.urls')),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/invite/$',
        views.org_member_invite, 
        {'template_name': 'org/org_member_invite.html'},
        name='org_org_member_invite'),
    #(r'^(?P<org_short_name>[\w_-]{1,20})/forum/$',include('forum.urls')),     
    url(r'^(?P<org_short_name>[\w_-]{1,20})/calendar/',
        include('evesch.ecalendar.urls')),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/reports/',
        include('evesch.report.urls')),    
    url(r'^(?P<org_short_name>[\w_-]{1,20})/feed_(?P<org_feed_hash>\w{1,20}).rss$', 
        feed_views.org_rss, {},
        name='core_feed_org_rss'),
    url(r'^(?P<org_short_name>[\w_-]{1,20})/ical_(?P<org_feed_hash>\w{1,20}).ics$',
        feed_views.org_ics, {},
        name='core_feed_org_ics'),
]
