from django.conf.urls import url
from evesch.event import views

urlpatterns = [
    url(r'^event/add/$',
        views.event_add,
        {'template_name': 'event/event_add.html'},
        name='event_event_add'),
    #url(r'^event/view/(?P<event_id>\w{1,10})/$','event
    #     views.event_view,
        #      {'template_name': 'error.html'},
        # name='event_event_view'),
    url(r'^event/(?P<event_hash>\w{1,8})/$',
        views.event_view,
        {'template_name': 'event/event_view.html'},
        name='event_event_view'),
    url(r'^event/(?P<event_hash>\w{1,8})/edit/$',
        views.event_edit,
        {'template_name': 'event/event_edit.html'},
        name='event_event_edit'),
    url(r'^event/(?P<event_hash>\w{1,8})/remove/$',
        views.event_remove,
        {'template_name': 'event/event_remove.html'},
        name='event_event_remove'),
    url(r'^event/(?P<event_hash>\w{1,8})/attendee/add/$',
        views.event_attendee_add,
        {'template_name': 'event/event_attendee_add.html'},
        name='event_attendee_add'),
    url(r'^event/(?P<event_hash>\w{1,8})/attendee/(?P<att_name>\w{3,30})/remove/$',
        views.event_attendee_remove,
        {'template_name': 'event/event_attendee_remove.html'},
        name='event_attendee_remove'),
    url(r'^event/(?P<event_hash>\w{1,8})/attendees/message/$',
        views.event_attendees_message,
        {'template_name': 'core/message_users.html'},
        name='event_attendees_message'),
    url(r'^events/$',
        views.events_list,
        {'template_name': 'event/events_list.html'},
        name='event_events_list'),
    url(r'^eventtype/add/$',
        views.eventtype_add,
        {'template_name': 'event/eventtype_add.html'},
        name='event_eventtype_add'),
    url(r'^eventtype/(?P<eventtype_hash>\w{1,8})/edit/$',
        views.eventtype_edit,
        {'template_name': 'event/eventtype_edit.html'},
        name='event_eventtype_edit'),
    url(r'^eventtype/(?P<eventtype_hash>\w{1,8})/remove/$',
        views.eventtype_remove,
        {'template_name': 'event/eventtype_remove.html'},
        name='event_eventtype_remove'),
]
